#!/usr/bin/env python

print("")
print("input text to turn into spoilers")
print("please use quotation marks around the text")

copypastaText = input()

copypastaText = copypastaText.replace("a", "||a||")
copypastaText = copypastaText.replace("b", "||b||")
copypastaText = copypastaText.replace("c", "||c||")
copypastaText = copypastaText.replace("d", "||d||")
copypastaText = copypastaText.replace("e", "||e||")
copypastaText = copypastaText.replace("f", "||f||")
copypastaText = copypastaText.replace("g", "||g||")
copypastaText = copypastaText.replace("h", "||h||")
copypastaText = copypastaText.replace("i", "||i||")
copypastaText = copypastaText.replace("j", "||j||")
copypastaText = copypastaText.replace("k", "||k||")
copypastaText = copypastaText.replace("l", "||l||")
copypastaText = copypastaText.replace("m", "||m||")
copypastaText = copypastaText.replace("n", "||n||")
copypastaText = copypastaText.replace("o", "||o||")
copypastaText = copypastaText.replace("p", "||p||")
copypastaText = copypastaText.replace("q", "||q||")
copypastaText = copypastaText.replace("r", "||r||")
copypastaText = copypastaText.replace("s", "||s||")
copypastaText = copypastaText.replace("t", "||t||")
copypastaText = copypastaText.replace("u", "||u||")
copypastaText = copypastaText.replace("v", "||v||")
copypastaText = copypastaText.replace("w", "||w||")
copypastaText = copypastaText.replace("x", "||x||")
copypastaText = copypastaText.replace("y", "||y||")
copypastaText = copypastaText.replace("z", "||z||")
copypastaText = copypastaText.replace("1", "||1||")
copypastaText = copypastaText.replace("2", "||2||")
copypastaText = copypastaText.replace("3", "||3||")
copypastaText = copypastaText.replace("4", "||4||")
copypastaText = copypastaText.replace("5", "||5||")
copypastaText = copypastaText.replace("6", "||6||")
copypastaText = copypastaText.replace("7", "||7||")
copypastaText = copypastaText.replace("8", "||8||")
copypastaText = copypastaText.replace("9", "||9||")
copypastaText = copypastaText.replace("0", "||0||")

print("")
print("copypasta text, copy this:")
print(copypastaText)
print("")
input("press enter to exit")
